#| filename: "deployment/deployment.yaml"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngg-deployment
  labels:
    app: ngg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngg
  template:
    metadata:
      labels:
        app: ngg
    spec:
      containers:
      - name: ngg
        image: leostep/fastapi-mlflow:latest
        ports:
        - containerPort: 8000
        - containerPort: 5000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "https://user-lstepien-mlflow.user.lab.sspcloud.fr"
        - name: MLFLOW_TRACKING_USERNAME
          value: "secret"  # Replace with your SSPCloud username
        - name: MLFLOW_TRACKING_PASSWORD
          value: "secret"  # Replace with your SSPCloud password