#| filename: "deployment/deployment.yaml"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngg-deployment
  labels:
    app: ngg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngg
  template:
    metadata:
      labels:
        app: ngg
    spec:
      containers:
      - name: ngg
        image: leostep/fastapi-mlflow:latest
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://localhost:5000"
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"